fragment PageParts on Page {
  __typename
  title
  description
  heroImage
  body
}

fragment PlantParts on Plant {
  __typename
  name
  scientificName
  category
  image
  season
  description
}

fragment GalleryParts on Gallery {
  __typename
  photos {
    __typename
    src
    alt
    caption
  }
}

fragment BosklasParts on Bosklas {
  __typename
  title
  description
  features {
    __typename
    text
  }
  photos {
    __typename
    src
    caption
  }
}

fragment ContactParts on Contact {
  __typename
  address
  rules {
    __typename
    allowed
    notAllowed
  }
  legalNotice
}
